"""Add newly pdf and audio column

Revision ID: 5f06e2e10452
Revises: e0eeb9081afb
Create Date: 2025-10-06 13:33:54.829968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f06e2e10452'
down_revision: Union[str, Sequence[str], None] = 'e0eeb9081afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_pdf', sa.String(), nullable=True))
    op.add_column('books', sa.Column('book_audio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_audio')
    op.drop_column('books', 'book_pdf')
    # ### end Alembic commands ###
