"""add featured column in book table

Revision ID: 882bfd1c5991
Revises: 2345d6f60aa8
Create Date: 2025-10-15 17:54:49.318992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882bfd1c5991'
down_revision: Union[str, Sequence[str], None] = '2345d6f60aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'featured')
    # ### end Alembic commands ###
