"""update donation table

Revision ID: 8ddde3798529
Revises: 5f06e2e10452
Create Date: 2025-10-07 16:38:27.886859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ddde3798529'
down_revision: Union[str, Sequence[str], None] = '5f06e2e10452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation_books', sa.Column('book_pdf', sa.String(), nullable=True))
    op.add_column('donation_books', sa.Column('book_audio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation_books', 'book_audio')
    op.drop_column('donation_books', 'book_pdf')
    # ### end Alembic commands ###
