"""add donation_books table

Revision ID: b09f7a70cb26
Revises: e1e913115021
Create Date: 2025-09-26 18:56:19.496966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09f7a70cb26'
down_revision: Union[str, Sequence[str], None] = 'e1e913115021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_books',
    sa.Column('d_book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_title', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_title', sa.String(length=200), nullable=False),
    sa.Column('book_author', sa.String(length=150), nullable=False),
    sa.Column('BS_mail', sa.String(length=150), nullable=False),
    sa.Column('BS_ID', sa.String(length=100), nullable=True),
    sa.Column('book_detail', sa.String(), nullable=True),
    sa.Column('book_photo', sa.String(), nullable=True),
    sa.Column('book_count', sa.Integer(), nullable=True),
    sa.Column('book_approve', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('d_book_id')
    )
    op.create_index(op.f('ix_donation_books_d_book_id'), 'donation_books', ['d_book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donation_books_d_book_id'), table_name='donation_books')
    op.drop_table('donation_books')
    # ### end Alembic commands ###
