"""Change book_approve to String

Revision ID: e0eeb9081afb
Revises: b09f7a70cb26
Create Date: 2025-09-29 15:19:24.481392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0eeb9081afb'
down_revision: Union[str, Sequence[str], None] = 'b09f7a70cb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donation_books', 'BS_ID',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('donation_books', 'book_approve',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('ix_donation_books_d_book_id', table_name='donation_books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_donation_books_d_book_id', 'donation_books', ['d_book_id'], unique=False)
    op.alter_column('donation_books', 'book_approve',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('donation_books', 'BS_ID',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
